language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cmake
      - nvidia-cuda-toolkit
      - nvidia-cuda-dev
      - nvidia-profiler
      
script:
  - export CXX=g++-8
  - mkdir build
  - cd build

  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON ..
  - make -j
  
  - cd ..
  - rm -r build
  - mkdir build
  
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_WITH_CUDA=ON ..
  - make -j

