dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cmake
      - libglm-dev
      - nvidia-cuda-toolkit
      - nvidia-cuda-dev
      - nvidia-profiler
      
script:
  - export CXX=g++-8

  - mkdir build-glm
  - cd build-glm
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_WITH_CUDA=OFF -DUSE_GLM=ON ..
  - make -j
  - cd ..

  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_WITH_CUDA=OFF ..
  - make -j
  - cd ..

  - mkdir build-cuda
  - cd build-cuda  
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_WITH_CUDA=ON ..
  - make -j
  - cd ..

