version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu

install:
- git submodule update --init --recursive

build_script:

- cmd: >-
    mkdir build && cd build

    cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release ..
    
    cmake --build . --config Release


- sh: >-
    mkdir build && cd build

    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    
    cmake --build . --config Release
