version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu1804

install:
- git submodule update --init --recursive

build_script:

- cmd: >-
    cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release

    cmake --build . -- -property:Configuration=Release

- sh: >-
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

    cmake --build .


