version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu1804

install:
- git submodule update --init --recursive

build_script:

- cmd: >-
    mkdir build && cd build

    cmake -G "Visual Studio 16 2019 x64" -DCMAKE_BUILD_TYPE=Release -DRENDER_MODULE="CPU (RayTracing)" ..
    cmake --build . --config Release
    
    #
    # check for cuda support on appveyor
    #
    #cmake -G "Visual Studio 16 2019 x64" -DCMAKE_BUILD_TYPE=Release -DRENDER_MODULE="CUDA (RayTracing)" ..
    #cmake --build . --config Release
    
    cmake -G "Visual Studio 16 2019 x64" -DCMAKE_BUILD_TYPE=Release -DRENDER_MODULE="OpenGL (Raster)" ..
    cmake --build . --config Release

- sh: >-
    mkdir build && cd build

    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DRENDER_MODULE="CPU (RayTracing)" ..
    cmake --build . --config Release
    
    #
    # check for cuda support on appveyor
    #
    #cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DRENDER_MODULE="CUDA (RayTracing)" ..
    #cmake --build . --config Release
    
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DRENDER_MODULE="OpenGL (Raster)" ..
    cmake --build . --config Release
