version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu1804

install:
- git submodule update --init --recursive

build_script:

- cmd: >-
    mkdir build && cd build

    cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DTRACY_RENDER_MODULE="CPU (RayTracing)" ..
    
    cmake --build . --config Release
    
    cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DTRACY_RENDER_MODULE="OpenGL (Raster)" ..
    
    cmake --build . --config Release

- sh: >-
    mkdir build && cd build

    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DTRACY_RENDER_MODULE="CPU (RayTracing)" ..
    
    cmake --build . --config Release


#
# Disabled Configurations
#

# CUDA support for both vs2019 and g++ is missing
#cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DTRACY_RENDER_MODULE="CUDA (RayTracing)" ..    
#cmake --build . --config Release

# CMake won't find OpenGL on linux
#cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DTRACY_RENDER_MODULE="OpenGL (Raster)" ..
#cmake --build . --config Release
