version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu

install:
- git submodule update --init --recursive

build_script:

- cmd: >-
    cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DUSE_GUI=ON

    cmake --build . -- -property:Configuration=Release

- sh: >-
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_GUI=ON

    cmake --build .


